iron_bank/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from app.views import SignUpView, AccountNumberList, AccountCreateView, AccountDetailView, TransactionCreateView, TransactionListView, TransferCreateView, TransactionDetailView, OverDraftView, \
    TransferListView, homepage, TransferDetailView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', homepage),
    url(r'^signup/$', SignUpView.as_view(), name="signup_view"),
    url(r'^login/$', auth_views.login, name="login_view"),
    url(r'^logout/$', auth_views.logout_then_login, name="logout_view"),
    url(r'^transactionlist/(?P<pk>\d+)/$', TransactionListView.as_view(), name="trans_list_view"),
    url(r'^accountlist/$', AccountNumberList.as_view(), name="account_list_view"),
    url(r'^accountcreate/$', AccountCreateView.as_view(), name="create_account_view"),
    url(r'^accountdetail/(?P<pk>\d+)/$', AccountDetailView.as_view(), name="account_detail_view"),
    url(r'^createtransaction/(?P<pk>\d+)/$', TransactionCreateView.as_view(), name="trans_create_view"),
    url(r'^transactiondetail/(?P<pk>\d+)/$', TransactionDetailView.as_view(), name="trans_detail_view"),
    url(r'^transfer/(?P<pk>\d+)/$', TransferCreateView.as_view(), name="transfer_create_view"),
    url(r'^overdraft/', OverDraftView.as_view(), name="over_view"),
    url(r'^transferlist/$', TransferListView.as_view(), name="transfer_list_view"),
    url(r'^transferdetails/(?P<pk>\d+)', TransferDetailView.as_view(), name="transfer_detail_view")
]

app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
TYPE_CHOICES = [('w', 'withdrawal'), ('d', 'deposit')]


class AccountNumber(models.Model):
    nickname = models.CharField(max_length=20)
    balance = models.IntegerField()
    user = models.ForeignKey(User)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} {}".format(self.user, self.nickname)


class Transaction(models.Model):
    account = models.ForeignKey(AccountNumber)
    trans_type = models.CharField(max_length=3, choices=TYPE_CHOICES)
    amount = models.IntegerField()
    description = models.CharField(max_length=50)
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-time_created"]


class Transfer(models.Model):
    account = models.ForeignKey(AccountNumber)
    amount = models.IntegerField()
    time_created = models.DateTimeField(auto_now_add=True)

app/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, TemplateView
from app.models import AccountNumber, Transaction, Transfer
how_many_days = 30


class LimitedAccessMixin:

    def get_queryset(self):
        return AccountNumber.objects.filter(user=self.request.user)


class SignUpView(CreateView):
    model = User
    form_class = UserCreationForm

    def get_success_url(self):
        return reverse("login_view")


def homepage(request):
    return HttpResponseRedirect(reverse('login_view'))


class AccountNumberList(LimitedAccessMixin, ListView):
    model = AccountNumber


class AccountCreateView(CreateView):
    model = AccountNumber
    fields = ('nickname', 'balance')

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("account_list_view")


class AccountDetailView(LimitedAccessMixin, DetailView):
    model = AccountNumber


class TransactionCreateView(CreateView):
    model = Transaction
    fields = ('trans_type', 'amount', 'description')

    def form_valid(self, form):
        form_object = form.save(commit=False)
        acct_num = AccountNumber.objects.get(pk=self.kwargs['pk'])
        form_object.account = acct_num
        if form_object.account.balance > 0:
            if form_object.trans_type == 'd':
                form_object.account.balance + form_object.amount
                form_object.account.save()
            elif form_object.trans_type == 'w':
                if form_object.amount > acct_num.balance:
                    return HttpResponseRedirect('/overdraft')
                else:
                    form_object.account.balance + form_object.amount
                    form_object.account.save()
            return super().form_valid(form)
        else:
            return HttpResponseRedirect('/overdraft')

    def get_success_url(self):
        return reverse("account_list_view")


class TransactionListView(ListView):
    model = Transaction

    def get_queryset(self):
        transactions_by_user = Transaction.objects.filter(account=self.kwargs['pk'])
        return transactions_by_user


class TransactionDetailView(DetailView):
    model = Transaction


class TransferCreateView(CreateView):
    model = Transfer
    fields = ('account', 'amount')

    def form_valid(self, form):
        form_object = form.save(commit=False)
        acct_num_from = AccountNumber.objects.get(pk=self.kwargs['pk'])
        if acct_num_from == AccountNumber:
            new_balance_from = acct_num_from.balance - form_object.amount
            new_balance_to = form_object.balance + form_object.amount
            if new_balance_from < 0:
                return HttpResponseRedirect('/overdraft')
            elif new_balance_to < 0:
                return HttpResponseRedirect('/overdraft')
            else:
                AccountNumber.objects.filter(pk=form_object.account.id).update(balance=new_balance_to)
                AccountNumber.objects.filter(pk=self.kwargs['pk']).update(balance=new_balance_from)
                form_object.save()
                return super().form_valid(form)
        else:
            return HttpResponseRedirect('/overdraft')

    def get_success_url(self):
        return reverse("account_list_view")


class OverDraftView(TemplateView):
    template_name = 'overdraft.html'


class TransferListView(ListView):
    model = Transfer


class TransferDetailView(DetailView):
    model = Transfer

templates/app/accountnumber_detail.html
{% extends 'base.html' %}

{% block content %}
    <h5>Account: {{ object.nickname }} - Details</h5>
    <br>
    <table>
        <thead>
          <tr>
              <th>Account Number</th>
              <th>Balance</th>
              <th>Account Owner</th>
              <th>Date Opened</th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td>{{ object.id }}</td>
            <td>$ {{ object.balance }}</td>
            <td>{{ object.user }}</td>
            <td>{{ object.time_created }}</td>

        </tbody>
      </table>
    <div class="'spacing">
    <a href="{% url 'trans_create_view' object.id %}" class="waves-effect waves-light btn">New Transaction</a>
    <a href="{% url 'trans_list_view' object.id %}" class="waves-effect waves-light btn">Transactions</a>
    <br><a href="{% url 'transfer_create_view' object.id %}" class="waves-effect waves-light btn">New Transfer</a>
    <a href="{% url 'transfer_list_view' %}" class="waves-effect waves-light btn">Transfers</a>
    </div>
{% endblock %}

templates/app/accountnumber_form.html
{% extends 'base.html' %}

{% block content %}
    <h5>Create an Account</h5>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
       <button class="btn waves-effect waves-light" type="submit" name="action">Create
            <i class="material-icons right">send</i>
        </button>
    </form>
{% endblock %}

templates/app/accountnumber_list.html
{% extends 'base.html' %}

{% block content %}
    <h5>Your accounts list</h5>
    <h6>Click on account for details</h6>
    <table>
        <thead>
          <tr>
              <th>Account Number</th>
              <th>Account Nickname</th>
              <th>Account Opened</th>
          </tr>
        </thead>
        <tbody>
        {% for account in object_list %}
          <tr>
            <td><a href="{% url 'account_detail_view' account.id %}">{{ account.id }}</a></td>
            <td><a href="{% url 'account_detail_view' account.id %}">{{ account.nickname }}</a></td>
            <td><a href="{% url 'account_detail_view' account.id %}">{{ account.time_created }}</a></td>

          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock %}

templates/app/transaction_detail.html
{% extends 'base.html' %}

{% block content %}
    <h5>Account: {{ object.account }} / Transaction Number {{ object.id }} -  Details</h5>
    <table>
        <thead>
          <tr>
              <th>Transaction Number</th>
              <th>Amount</th>
              <th>Type</th>
              <th>Created</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ object.id }}</td>
            <td>$ {{ object.amount }}</td>
            <td>{{ object.get_trans_type_display }}</td>
            <td>{{ object.time_created }}</td>
        </tr>
        </tbody>
      </table>
    <a href="{% url 'trans_create_view' object.account.id %}" class="waves-effect waves-light btn">New Transaction</a>
{% endblock %}

templates/app/transaction_form.html
{% extends 'base.html' %}

{% block content %}
    <h5>{{ request.user }} - Create a Transaction</h5>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Create
            <i class="material-icons right">send</i>
        </button>
    </form>
{% endblock %}

templates/app/transaction_list.html
{% extends 'base.html' %}

{% block content %}
    <h5>Your transaction list</h5>
    <h6>Click on transaction for details</h6>
    <table>
        <thead>
          <tr>
              <th>Type of Transaction</th>
              <th>Amount of Transation</th>
          </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
          <tr>
            <td><a href="{% url 'trans_detail_view' transaction.id %}">{{ transaction.get_trans_type_display }}</a></td>
            <td><a href="{% url 'trans_detail_view' transaction.id %}">$ {{ transaction.amount }}</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock %}

templates/app/transfer_detail.html
{% extends 'base.html' %}

{% block content %}
    <h5>Transaction: {{ object.id }} - Details</h5>
    <br>
    <table>
        <thead>
          <tr>
              <th>Transaction Number</th>
              <th>Amount</th>
              <th>Transfered To:</th>
              <th>Time</th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td>{{ object.id }}</td>
            <td>$ {{ object.amount }}</td>
              <td>{{ object.account }}</td>
              <td>{{ object.time_created }}</td>
            </tr>
        </tbody>
      </table>
{% endblock %}

templates/app/transfer_form.html
{% extends 'base.html' %}

{% block content %}
    <h5>{{ request.user }} - Create a Transfer</h5>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Create
            <i class="material-icons right">send</i>
        </button>
    </form>
{% endblock %}

templates/app/transfer_list.html
{% extends 'base.html' %}

{% block content %}
    <h5>Your Transfer list</h5>
    <table>
        <thead>
          <tr>
              <th>Account</th>
              <th>Amount</th>
              <th>User</th>
          </tr>
        </thead>
        <tbody>
        {% for account in object_list %}
          <tr>
            <td><a href="{% url 'transfer_detail_view' account.id %}">{{ account.account.nickname }}</a></td>
            <td><a href="{% url 'transfer_detail_view' account.id %}">{{ account.amount }}</a></td>
            <td><a href="{% url 'transfer_detail_view' account.id %}">{{ account.account.user }}</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <title>IronBank</title>
</head>
<body>
    <div class="container">

    <nav>
        <div class="nav-wrapper">
          <ul class="right hide-on-med-and-down">
            {% if request.user.is_authenticated %}
              <li><a href="{% url 'account_list_view' %}" >account list</a></li>
              <li><a href="{% url 'create_account_view' %}" >create account</a></li>
              <li><a href="{% url 'logout_view' %}" >{{ request.user }}, logout</a></li>
            {% else %}
              <li><a href="{% url 'signup_view' %}">signup</a></li>
              <li><a href="{% url 'login_view' %}">login</a></li>
            {% endif %}
          </ul>
            <ul class="side-nav" id="mobile-demo">
            {% if request.user.is_authenticated %}
              <li><a href="{% url 'account_list_view' %}" >account list</a></li>
              <li><a href="{% url 'create_account_view' %}" >create account</a></li>
              <li><a href="{% url 'logout_view' %}" >{{ request.user }}, logout</a></li>
            {% else %}
              <li><a href="{% url 'signup_view' %}">signup</a></li>
              <li><a href="{% url 'login_view' %}">login</a></li>
            {% endif %}

        </div>
    </nav>

    {% if request.user.is_authenticated %}
    <div id="span"><h5>Welcome {{ request.user }}</h5></div>
    {% endif %}
        {% block content %}
        {% endblock %}
    </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
<script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
<script type="">
    $( document ).ready(function(){
    $(".button-collapse").sideNav(); });
</script>
</body>
</html>

templates/overdraft.html
{% extends 'base.html' %}

{% block content %}
        <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h4 class="white-text">Error</h4>
                <p class="grey-text text-lighten-4">You cannot over draw your account or access accounts that do not belong to you.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h6 class="white-text">Thank you for banking with the most ultimate Bank in the universe.  Have a nice day.</h6>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2016 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!"></a>
            </div>
          </div>
        </footer>
{% endblock %}